export const categories = [
  {
    id: 'casual',
    name: 'Casual',
    description: 'Everyday comfortable blouses',
    image: '/b1.jpg',
  },
  {
    id: 'formal',
    name: 'Formal',
    description: 'Elegant blouses for professional settings',
    image: '/b2.jpg',
  },
  {
    id: 'evening',
    name: 'Evening',
    description: 'Glamorous blouses for special occasions',
    image: '/b3.jpg',
  },
  {
    id: 'summer',
    name: 'Summer',
    description: 'Light and breezy blouses for warm weather',
    image: '/b4.jpg',
  },
];

export const products = [
  {
    id: '1',
    name: 'Silk Casual Blouse',
    category: 'casual',
    image: '/b1.jpg',
    description: 'A soft silk blouse perfect for everyday wear. Made from premium 100% silk with a comfortable fit and elegant drape.',
    price: 'Contact for pricing',
    rating: 4.8,
    reviewCount: 24,
    material: '100% Silk',
    care: 'Dry clean only',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Navy'],
    features: ['Breathable fabric', 'Elegant drape', 'Comfortable fit', 'Versatile styling'],
    details: 'This luxurious silk blouse features a classic collar and button-front design. The fabric is lightweight yet substantial, providing both comfort and sophistication. Perfect for office wear, casual outings, or layering under jackets.',
  },
  {
    id: '2',
    name: 'Tailored Formal Blouse',
    category: 'formal',
    image: '/b2.jpg',
    description: 'Elegant tailored blouse for the office. Professional design with crisp lines and sophisticated styling.',
    price: 'Contact for pricing',
    rating: 4.9,
    reviewCount: 31,
    material: 'Cotton Blend',
    care: 'Machine wash cold',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Light Blue', 'Gray'],
    features: ['Wrinkle-resistant', 'Professional fit', 'Button cuffs', 'Classic collar'],
    details: 'Designed for the modern professional, this tailored blouse combines comfort with sophistication. The structured fit and high-quality fabric ensure you look polished throughout your workday.',
  },
  {
    id: '3',
    name: 'Sequined Evening Blouse',
    category: 'evening',
    image: '/b3.jpg',
    description: 'Sparkling sequined blouse for evening events. Glamorous design that catches the light beautifully.',
    price: 'Contact for pricing',
    rating: 4.7,
    reviewCount: 18,
    material: 'Silk with sequins',
    care: 'Dry clean only',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Silver', 'Gold', 'Black'],
    features: ['Shimmering sequins', 'Elegant neckline', 'Fitted silhouette', 'Evening glamour'],
    details: 'Make a statement at your next special event with this stunning sequined blouse. The intricate sequin work catches the light beautifully, creating a mesmerizing effect that will turn heads.',
  },
  {
    id: '4',
    name: 'Cotton Summer Blouse',
    category: 'summer',
    image: '/b4.jpg',
    description: 'Breathable cotton blouse for summer days. Light and airy fabric perfect for warm weather.',
    price: 'Contact for pricing',
    rating: 4.6,
    reviewCount: 22,
    material: '100% Organic Cotton',
    care: 'Machine wash warm',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Pastel Pink', 'Light Blue'],
    features: ['Breathable fabric', 'Moisture-wicking', 'Lightweight', 'Summer ready'],
    details: 'Stay cool and comfortable during hot summer days with this breathable cotton blouse. The organic cotton fabric is soft against your skin and provides excellent ventilation.',
  },
  {
    id: '5',
    name: 'Chiffon Blouse',
    category: 'casual',
    image: '/b5.jpg',
    description: 'Light chiffon blouse for casual outings. Flowy and feminine with delicate fabric.',
    price: 'Contact for pricing',
    rating: 4.5,
    reviewCount: 16,
    material: 'Polyester Chiffon',
    care: 'Hand wash cold',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Cream', 'Light Pink'],
    features: ['Flowy silhouette', 'Delicate fabric', 'Feminine design', 'Layering piece'],
    details: 'This chiffon blouse adds a touch of romance to your wardrobe. The lightweight fabric flows beautifully with movement, creating an elegant and feminine silhouette.',
  },
  {
    id: '6',
    name: 'Button-Down Blouse',
    category: 'formal',
    image: '/b6.jpg',
    description: 'Classic button-down for formal occasions. Timeless design with modern tailoring.',
    price: 'Contact for pricing',
    rating: 4.8,
    reviewCount: 29,
    material: 'Cotton Poplin',
    care: 'Machine wash cold',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Light Blue', 'Striped'],
    features: ['Button-front closure', 'Collared neckline', 'Cuffed sleeves', 'Tailored fit'],
    details: 'A wardrobe essential, this button-down blouse combines classic styling with modern tailoring. The crisp cotton fabric maintains its shape throughout the day.',
  },
  {
    id: '7',
    name: 'Satin Evening Blouse',
    category: 'evening',
    image: '/b7.jpg',
    description: 'Luxurious satin blouse for evenings. Smooth fabric with elegant sheen.',
    price: 'Contact for pricing',
    rating: 4.9,
    reviewCount: 25,
    material: 'Satin Silk',
    care: 'Dry clean only',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Burgundy', 'Emerald'],
    features: ['Luxurious satin', 'Elegant sheen', 'Draped design', 'Evening sophistication'],
    details: 'Elevate your evening look with this luxurious satin blouse. The smooth fabric drapes beautifully and catches the light with an elegant sheen that adds instant glamour.',
  },
  {
    id: '8',
    name: 'Linen Summer Blouse',
    category: 'summer',
    image: '/b8.jpg',
    description: 'Cool linen blouse for hot days. Natural fiber that breathes and regulates temperature.',
    price: 'Contact for pricing',
    rating: 4.7,
    reviewCount: 20,
    material: '100% Linen',
    care: 'Machine wash cold',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Natural', 'Light Gray', 'Sage Green'],
    features: ['Temperature regulating', 'Breathable', 'Natural texture', 'Sustainable'],
    details: 'Experience the cooling properties of linen with this summer blouse. The natural fiber wicks away moisture and regulates your body temperature for all-day comfort.',
  },
  {
    id: '9',
    name: 'Tulle Blouse',
    category: 'evening',
    image: '/b9.jpg',
    description: 'Delicate tulle blouse for special events. Romantic and ethereal design.',
    price: 'Contact for pricing',
    rating: 4.6,
    reviewCount: 14,
    material: 'Nylon Tulle',
    care: 'Dry clean only',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Champagne', 'Rose Gold'],
    features: ['Delicate tulle', 'Romantic design', 'Layered effect', 'Special occasion'],
    details: 'Create a fairy-tale look with this delicate tulle blouse. The layered fabric creates a romantic, ethereal effect perfect for weddings, galas, and other special events.',
  },
  {
    id: '10',
    name: 'Denim Blouse',
    category: 'casual',
    image: '/b10.jpg',
    description: 'Stylish denim blouse for casual wear. Versatile piece that transitions from day to night.',
    price: 'Contact for pricing',
    rating: 4.8,
    reviewCount: 27,
    material: 'Cotton Denim',
    care: 'Machine wash cold',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Light Blue', 'Dark Wash', 'White'],
    features: ['Classic denim', 'Button-front', 'Roll-up sleeves', 'Versatile styling'],
    details: 'A casual wardrobe staple, this denim blouse offers endless styling possibilities. The quality denim fabric is comfortable and durable, making it perfect for everyday wear.',
  },
];

export const bestWorks = [
  // Similar to products, highlight some
];